const BAD_REQUEST_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const REQUEST_SUCCESS = 200;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const CONFLICT_ERROR = 409;

const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST_ERROR, NOT_FOUND_ERROR, INTERNAL_SERVER_ERROR, REQUEST_SUCCESS, UNAUTHORIZED_ERROR, FORBIDDEN_ERROR
};